version: '3'
services:
  db:
    image: "postgres:13.4"
    container_name: api-db
    user: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=apiDbUser
      - POSTGRES_PASSWORD=apiDbPassword
      - POSTGRES_DB=apiDb
    ports:
      - "5433:5432"
